name: staging-deploy-actions
on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm install --force

      - name: Create env file
        run: |
          touch ./.env.staging
          cat << EOF >> ./.env.staging 
          ${{ secrets.STAGING }}

      - name: Build
        run: npm run build:staging

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
          build s3://admin.staging.mecrosspro.com

      - name: Slack notification success
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: mecrosspro
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: 'admin staging에 배포했습니다.'

      - name: Slack notification failure
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: 'admin staging 배포에 실패했습니다. https://github.com/OneTwoAd/new-mecrosspro-admin-frontend/actions'
        if: failure()
